version: '3'

services:
  room-web:
    image: room-web
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - STAGE=prod
      - VERSION=1.0-production
    ports:
      - 80:80
